### ISSUE TITLE
Can I use parts of this in my project?

### ISSUE THREAD

**Issue by alichtman** [cbergoon/macos-restic-backup#1]
https://github.com/alichtman/shallow-backup

I'm planning on adding automatic restic backups to my back up utility. I'm asking for permission because I noticed there was no license in the repo. Is that okay?

**Comment by cbergoon** [comment]
Yep, of course. I added a MIT license - hope that works for you.  I never considered a use case outside of a personal utility. 

p.s. It's only ever been used/tested on my environment as far as I know - so I will welcome any improvements you make. 

Cam

**Comment by alichtman** [comment]
MIT is perfect. I'll open PRs for any necessary changes. Thanks!
